default_number_of_speech_rec_alternatives = 10
default_number_of_nlp_threads = 10

ws_port = 7004

companies = {
    "III": ["3I GRP", "3i Group"],
    "ABF": ["A.B.FOOD", "Associated Brititsh Foods"],
    "ADM": ["ADMIRAL GRP", "Admiral Group"],
    "AAL": ["ANGLO AMERICAN"],
    "ANTO": ["ANTOFAGASTA"],
    "AHT": ["ASHTEAD GRP.", "Ashtead Group"],
    "AZN": ["ASTRAZENCA"],
    "AV.": ["AVIVA"],
    "BA.": ["BAE SYS.", "BAE systems"],
    "BARC": ["BARCLAYS"],
    "BDEV": ["BARRATT DEVL.", "Barratt Developments"],
    "BKG": ["BERKELEY GP. HLD", "Berkeley Group Holdings"],
    "BLT": ["BHP BILLITON"],
    "BP": ["BP", "British Petroleum"],
    "BATS": ["BR.AMER.TOB.", "British American Tobacco"],
    "BLND": ["BR.LAND", "British Land"],
    "BT.A": ["BT GROUP"],
    "BNZL": ["BUNZL"],
    "BRBY": ["BURBERRY GRP", "Burberry Group"],
    "CCL": ["CARNIVAL"],
    "CNA": ["CENTRICA"],
    "CCH": ["COCACOLA HBC AG", "Coca Cola Hellenic Bottling Company"],
    "CPG": ["COMPASS GROUP"],
    "CRH": ["CRH"],
    "CRDA": ["CRODA INTL.", "Croda International", "Croda"],
    "DCC": ["DCC"],
    "DGE": ["DIAGEO"],
    "DLG": ["DIRECT LINE"],
    "EZJ": ["EASY JET"],
    "EVR": ["EVRAZ"],
    "EXPN": ["EXPERIAN"],
    "FERG": ["FERGUSON"],
    "FRES": ["FRESNILLO"],
    "GFS": ["G4S"],
    "GKN": ["GKN"],
    "GSK": ["GLAXOSMITHKLINE", "Glaxo Smith Kline"],
    "GLEN": ["GLENCORE"],
    "HLMA": ["HALMA"],
    "HMSO": ["HAMMERSON"],
    "HL.": ["HARGREAVES LANS", "Hargreaves Lansdown"],
    "HSBA": ["HSBC HLDGS.UK", "HSBC Holdings", "HSBC"],
    "IMB": ["IMP.BRANDS", "Imperial Brands"],
    "INF": ["INFORMA"],
    "IHG": ["INTERCON. HOTEL", "Intercontinental Hotels Group"],
    "ITRK": ["INTERTEK GROUP"],
    "IAG": ["INTL CONSOL AIR", "International Consolidated Airlines Group"]
    "ITV": ["ITV"],
    "JMAT": ["JOHNSON MATTHEY", "Matthey", "FM"],
    "JE.": ["JUST EAT"],
    "KGF": ["KINGFISHER"],
    "LAND": ["LAND SECS.", "Land Securities"],
    "LGEN": ["LEGAL&GEN.", "Legal and General"],
    "LLOY": ["LLOYDS GRP.","Lloyds"],
    "LSE": ["LON.STK.EXCH", "London Stock Exchange"],
    "MKS": ["MARKS & SP.", "Marks and Spencer"],
    "MDC": ["MEDICLINIC"],
    "MCRO": ["MICRO FOCUS"],
    "MNDI": ["MONDI"],
    "MRW": ["MORRISON (WM)", "Morrison"],
    "NG.": ["NATIONAL GRID"],
    "NXT": ["NEXT"],
    "NMC": ["NMC HEALTH"],
    "OML": ["OLD MUTUAL"],
    "PPB": ["PADDY PWR BET", "Paddy Power Betfair"],
    "PSON": ["PEARSON"],
    "PSN": ["PERSIMMON"],
    "PRU": ["PRUDENTIAL"],
    "RRS": ["RANDGOLD RES.", "Randgold Resources Limited"],
    "RDSA": ["RDS 'A'", "Royal Dutch Shell A"],
    "RDSB": ["RDS 'B'", "Royal Dutch Shell B"],
    "RB.": ["RECKITT BEN. GP", "Reckitt Benckiser Group"],
    "REL": ["RELX"],
    "RTO": ["RENTOKIL INITL.", "Rentokil Initial"],
    "RIO": ["RIO TINTO"][],
    "RR.": ["ROLLS-ROYCE HLG", "Rolls Royce"],
    "RBS": ["ROYAL BANK SCOT", "Royal Bank of Scotland", "RBS"],
    "RSA": ["RSA INS.", "RSA Insurance"],
    "SGE": ["SAGE GRP.", "Sage Group"],
    "SBRY": ["SAINSBURY(J)", "J Sainsbury", "Sainsbury's"],
    "SDR": ["SCHRODERS"],
    "SMT": ["SCOTTISH MORT"],
    "SGRO": ["SEGRO"],
    "SVT": ["SEVERN TRENT"],
    "SHP": ["SHIRE"],
    "SKY": ["SKY PLC", "Sky"],
    "SN.": ["SMITH&NEPHEW", "Smith and Nephew"],
    "SMDS": ["SMITH(DS)", "DS Smith"],
    "SMIN": ["SMITHS GROUP"],
    "SKG": ["SMURFIT KAP.", "Smurfit Kappa"],
    "SSE": ["SSE", "Scottish and Southern Energy"],
    "STJ": ["ST.JAMES'S PLAC", "St James Place", "St James Place Wealth Management"],
    "STAN": ["STAND.CHART", "Standard Chartered"],
    "SLA": ["STD LIFE ABER", "Standard Life Aberdeen"],
    "TW.": ["TAYLOR WIMPEY"],
    "TSCO": ["TESCO"],
    "TUI": ["TUI AG", "Tui"],
    "ULVR": ["UNILEVER"],
    "UU.": ["UTD.UTILITES", "United Utilities"],
    "VOD": ["VODAFONE GRP.", "Vodafone"],
    "TWB": ["WHITBREAD"],
    "WWP": ["WWP"]
}

industries = {
    1: "Aerospace & Defence",
    2: "Alternative Energy",
    3: "Automobiles & Parts",
    4: "Banks",
    5: "Beverages",
    6: "Chemicals",
    7: "Construction & Materials",
    8: "Electricity",
    9: "Electronic & Electrical Equipment",
    10: "Equity Investment Instruments",
    11: "Financial Services",
    12: "Fixed Line Telecommunications",
    13: "Food & Drug Retailers",
    14: "Food Producers",
    15: "Forestry & Paper",
    16: "Gas, Water & Multiutilities",
    17: "General Industrials",
    18: "General Retailers",
    19: "Health Care Equipment & Services",
    20: "Household Goods & Home Construction",
    21: "Industrial Engineering",
    22: "Industrial Metals & Mining",
    23: "Industrial Transportation",
    24: "Leisure Goods",
    25: "Life Insurance",
    26: "Media",
    27: "Mining",
    28: "Mobile Telecommunications",
    29: "Nonequity Investment Instruments",
    30: "Nonlife Insurance",
    31: "Oil & Gas Producers",
    32: "Oil Equipment & Services",
    33: "Personal Goods",
    34: "Pharmaceuticals & Biotechnology",
    35: "Real Estate Investment & Services",
    36: "Real Estate Investment Trusts",
    37: "Software & Computer Services",
    38: "Support Services",
    39: "Technology Hardware & Equipment",
    40: "Tobacco",
    41: "Travel & Leisure"
}

import business_logic.nlp.data_tags as tags
companies_by_industry = {
    tags.Industry.pharma: []
}
