default_number_of_speech_rec_alternatives = 10
default_number_of_nlp_threads = 10

ws_port = 7004

companies = {
    "III": "3I GRP",
    "ABF": "A.B.FOOD",
    "ADM": "ADMIRAL GRP",
    "AAL": "ANGLO AMERICAN",
    "ANTO": "ANTOFAGASTA",
    "AHT": "ASHTEAD GRP.",
    "AZN": "ASTRAZENCA",
    "AV.": "AVIVA",
    "BA.": "BAE SYS.",
    "BARC": "BARCLAYS",
    "BDEV": "BARRAT DEVL.",
    "BKG": "BERKLEY GP. HLD",
    "BLT": "BHP BILLITON",
    "BP": "BP",
    "BATS": "BR.AMER.TOB.",
    "BLND": "BR.LAND",
    "BT.A": "BT GROUP",
    "BNZL": "BUNZL",
    "BRBY": "BURBERRY GRP",
    "CCL": "CARNIVAL",
    "CNA": "CENTRICA",
    "CCH": "COCACOLA HBC AG",
    "CPG": "COMPASS GROUP",
    "CRH": "CRH",
    "CRDA": "CRODA INTL.",
    "DCC": "DCC",
    "DGE": "DIAGEO",
    "DLG": "DIRECT LINE",
    "EZJ": "EASY JET",
    "EVR": "EVRAZ",
    "EXPN": "EXPERIAN",
    "FERG": "FERGUSON",
    "FRES": "FRESNILLO",
    "GFS": "G4S",
    "GKN": "GKN",
    "GSK": "GLAXOSMITHKLINE",
    "GLEN": "GLENCORE",
    "HLMA": "HALMA",
    "HMSO": "HAMMERSON",
    "HL.": "HARGREAVES LANS",
    "HSBA": "HSBC HLDGS.UK",
    "IMB": "IMP.BRANDS",
    "INF": "INFORMA",
    "IHG": "INTERCON. HOTEL",
    "ITRK": "INTERTEK GROUP",
    "IAG": "INTL CONSOL AIR",
    "ITV": "ITV",
    "JMAT": "JOHNSON MATTHEY",
    "JE.": "JUST EAT",
    "KGF": "KINGFISHER",
    "LAND": "LAND SECS.",
    "LGEN": "LEGAL&GEN.",
    "LLOY": "LLOYDS GRP.",
    "LSE": "LON.STK.EXCH",
    "MKS": "MARKS & SP.",
    "MDC": "MEDICLINIC",
    "MCRO": "MICRO FOCUS",
    "MNDI": "MONDI",
    "MRW": "MORRISON (WM)",
    "NG.": "NATIONAL GRID",
    "NXT": "NEXT",
    "NMC": "NMC HEALTH",
    "OML": "OLD MUTUAL",
    "PPB": "PADDY PWR BET",
    "PSON": "PEARSON",
    "PSN": "PERSIMMON",
    "PRU": "PRUDENTIAL",
    "RRS": "RANGOLDS RES.",
    "RDSA": "RDS 'A'",
    "RDSB": "RDS 'B'",
    "RB.": "RECKIT BEN. GP",
    "REL": "RELX",
    "RTO": "RENTOKIL INITL.",
    "RIO": "RIO TINTO",
    "RR.": "ROLLS-ROYCE HLG",
    "RBS": "ROYAL BANK SCOT",
    "RSA": "RSA INS.",
    "SGE": "SAGE GRP.",
    "SBRY": "SAINSBURY(J)",
    "SDR": "SCHRODERS",
    "SMT": "SCOTTISH MORT",
    "SGRO": "SEGRO",
    "SVT": "SEVERN TRENT",
    "SHP": "SHIRE",
    "SKY": "SKY PLC",
    "SN.": "SMITH&NEPHEW",
    "SMDS": "SMITH(DS)",
    "SMIN": "SMITHS GROUP",
    "SKG": "SMURFIT KAP.",
    "SSE": "SSE",
    "STJ": "ST.JAMES'S PLAC",
    "STAN": "STAND.CHART",
    "SLA": "STD LIFE ABER",
    "TW.": "TAYLOR WIMPEY",
    "TSCO": "TESCO",
    "TUI": "TUI AG",
    "ULVR": "UNILEVER",
    "UU.": "UTD.UTILITES",
    "VOD": "VODAFONE GRP.",
    "TWB": "WHITBREAD",
    "WWP": "WWP"
}

industries = {
    1: "Aerospace & Defence",
    2: "Alternative Energy",
    3: "Automobiles & Parts",
    4: "Banks",
    5: "Beverages",
    6: "Chemicals",
    7: "Construction & Materials",
    8: "Electricity",
    9: "Electronic & Electrical Equipment",
    10: "Equity Investment Instruments",
    11: "Financial Services",
    12: "Fixed Line Telecommunications",
    13: "Food & Drug Retailers",
    14: "Food Producers",
    15: "Forestry & Paper",
    16: "Gas, Water & Multiutilities",
    17: "General Industrials",
    18: "General Retailers",
    19: "Health Care Equipment & Services",
    20: "Household Goods & Home Construction",
    21: "Industrial Engineering",
    22: "Industrial Metals & Mining",
    23: "Industrial Transportation",
    24: "Leisure Goods",
    25: "Life Insurance",
    26: "Media",
    27: "Mining",
    28: "Mobile Telecommunications",
    29: "Nonequity Investment Instruments",
    30: "Nonlife Insurance",
    31: "Oil & Gas Producers",
    32: "Oil Equipment & Services",
    33: "Personal Goods",
    34: "Pharmaceuticals & Biotechnology",
    35: "Real Estate Investment & Services",
    36: "Real Estate Investment Trusts",
    37: "Software & Computer Services",
    38: "Support Services",
    39: "Technology Hardware & Equipment",
    40: "Tobacco",
    41: "Travel & Leisure"
}

import business_logic.nlp.data_tags as tags
companies_by_industry = {
    tags.Industry.pharma: []
}
